/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const proveedores_Logic = require('./code/proveedores-logic');

class appProductosProCodeSrv extends LCAPApplicationService {
    async init() {

        this.on('CREATE', 'Proveedores', async (request, next) => {
            return proveedores_Logic(request, next);
        });

        return super.init();
    }
}


module.exports = {
    appProductosProCodeSrv
};